### ISSUE TITLE
Funcionalidades de Fornecedor (show, add, edit, delete) 

### ISSUE THREAD

**Issue by natarajanrodrigues** [ads-ifpb-praticas-20161/siscultural#6]
Levar em consideração de que haverão 2 repositories: um para Pessoa Jurídica e outro para Física.

**Comment by victorhsr** [comment]
faltando o EDIT e DELETE

**Comment by victorhsr** [comment]
faltando o EDIT

**Comment by victorhsr** [comment]
Issue concluida neste [commit](https://github.com/ads-ifpb-praticas-20161/siscultural/commit/5dee4102f7771bcaa276e0b18ceebc2edcab2960)
