### ISSUE TITLE
Deletando um Contrato

### ISSUE THREAD

**Issue by natarajanrodrigues** [ads-ifpb-praticas-20161/siscultural#9]
Ao deletar o contrato deverá também deletar as Apresentações e Pagamentos relacionados ao contrato.

**Comment by victorhsr** [comment]
Se for apagar também os atributos presentation e paymentProposals, basta adicionar CascadeType.REMOVE na anotação JPA. Exemplo de como ficaria:

`@OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    private List<PaymentProposal> paymentProposals;`

**Comment by victorhsr** [comment]
Se for apagar também os atributos presentation e paymentProposals, basta adicionar CascadeType.REMOVE na anotação JPA. Exemplo de como ficaria:

```
@OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH, CascadeType.REMOVE})
private List<PaymentProposal> paymentProposals;
```

**Comment by natarajanrodrigues** [comment]
Massa. O `presentation` vai continuar. Vou adicionar só no `List<PaymentProposal> paymentProposals.`

**Comment by natarajanrodrigues** [comment]
Solved on [coment](https://github.com/ads-ifpb-praticas-20161/siscultural/commit/e74dd81ce829afa4af31d9a0e407a5489d7efa53)
